#!/bin/bash
#SBATCH -t 0:00:30
#SBATCH -n 2 -c 16
module load mpi/intel
module load bsponmpi c/intel
cd $HOME/Students17/zonomiwo/bsp_unique_chess
srun ./parallel4 1 6
                                          